### ISSUE TITLE
Touch gestures are too… touchy

### ISSUE THREAD

**Issue by mgsisk** [mgsisk/webcomic#206]
Touch gestures are a bit sensitive. Need to look into making them harder to activate when a user is just normally scrolling a page.

**Comment by jproffitt3ge** [comment]
Right now the touch gestures are not actually measuring what they should be. They currently measure "page" coordinates, which are where you are touching on the page rather the screen. The pageY coordinate doesn't really change between touch start and touch end if you are scrolling vertically so it misdirects it as a left/right gesture.

I rewrote the script to measure the average "client" coordinates, which are relative to the physical screen, but I wonder if it might be more prudent to delegate the raw gesture detection to a library like hammer.js.
