### ISSUE TITLE
Reveal post content for restricted webcomics

### ISSUE THREAD

**Issue by mgsisk** [mgsisk/webcomic#209]
It might be useful to show basic the post content (post, title) for age or role-restricted webcomics, while hiding the webcomic image itself. Interested in feedback on this one (thanks @mihari for the suggestion).

**Comment by mgsisk** [comment]
Still interested in feedback on this one. It would be a big change from how Webcomic handles restricted content right now.

**Comment by Mihari** [comment]
Well, you know my take on it!

**Comment by Mihari** [comment]
BUMP! Any updates on this?
