### ISSUE TITLE
navigation issues in Webcomic

### ISSUE THREAD

**Issue by monstertruckcomic** [mgsisk/webcomic#217]
I'm using webcomic over at www.monstertruckcomic.com.  It's been working great and I love it - today I uploaded new material and my navigation arrows are no longer responding properly.  When you hit one page forward, the url changes as if the page is advancing, but the actual page itself doesn't change.  Any ideas?

**Comment by monstertruckcomic** [comment]
Michael,

You've been great about helping me so far - I'm new to Wordpress and trying to run a small business without a developer.  I'm hoping you could answer another question for me.  I'm running Inkblot and I want my home page to be, basically, just an image, a logo, and a menu bar.  I want to get rid of the content box completely - I've created a blog page for that.  How do I do that?  Does my question make sense?  I've attached an image of what I basically want my home page to look like.  Thanks for your help!

Patrick Drury

**Comment by mgsisk** [comment]
No worries Patrick. It looks like your image didn't make it, but what you probably want to do is create a [static front page](http://codex.wordpress.org/Creating_a_Static_Front_Page). Newer versions of Inkblot also include a **Full Width** template, which should remove any sidebars without you having to mess around in the CSS. That should get you most (if not all) of the way there.

**Comment by monstertruckcomic** [comment]
Thanks for getting back to me Michael.  I'm not sure what I did, but my
content box covers the whole page now.  I can't see my background image at
all...  www.patchdrury.net

Also, I tried to reupload what I hope to get my home page to look like.

**Comment by mgsisk** [comment]
Apologies for taking so long to reply @monstertruckcomic. Assuming you haven't given up on this: it may be that your Inkblot Customizer settings are a bit screwy. Make sure the Maximum Width and Minimum Width settings have a value (however wide you want your site to be).
