### ISSUE TITLE
Any ETA on the possible age verification system?

### ISSUE THREAD

**Issue by Mihari** [mgsisk/webcomic#225]
Just a general question and wondering how this was coming, I know we talked way back in October and said it would be a thing in Novemeber. Holidays, life, and all that aside it's understood stuff gets in the way and it's not a problem. 

However, still waiting and need this, wondering when and / if we'll still see this any time soon?

**Comment by mgsisk** [comment]
Apologies Mihari. If we're referring specifically to #207 and #208, I am trying to have those finished up before the end of the month, possibly sooner. Once Inkblot is straightened out I'll be shifting gear to Webcomic.

**Comment by Mihari** [comment]
We've gabbed on about off and on in the various chats, ideally what would be nice is that whole overlay  blacking out adult content with the age verification (the simple yes / no) applied a top it. At the very least having the simplified (no date entry) version would be a nice start. Blacking out the content would just be a shiny way to still load the rest of the pages content on load of a marked adult comic.

**Comment by mgsisk** [comment]
That commit addresses at least two things I remember we spoke about: it simplifies the age verification (now it's just two buttons, one for "Yes, I'm X or older" and one for "No, I'm not X years old"; this will require changes to the restricted templates in themes) and it corrects the issue that was causing age (and role) restricted Webcomic images from incorrectly displaying on the homepage.

Hopefully this will do, as an overlay of some kind is really beyond what I would want Webcomic to provide here. It's still technically *doable*, but the implementation would be largely dependent on your theme and personal preference.

**Comment by sexkitten66** [comment]
Lol
