### ISSUE TITLE
Disqus Plugin & Header Plugin & Small Header Issue

### ISSUE THREAD

**Issue by gaiusjaugustus** [mgsisk/webcomic#227]
Cross posted on wordpress support page.
I'm working to get two things working on my site with Webcomic, and also have an issue; I hope you can help me with them.

1) Disqus: It works on every page of the comic out of the box with the Disqus plugin. However, the Disqus comments DON'T show up when using the Webcomic Homepage template. If I enable comments, it shows comments from ALL the comics in the series, not just the lastest comic. (Example: http://comics.theindigopath.com/the-fall-comic/ ) I assume it's because it's a page and not a post. Any workaround for this?

2) I'm trying to add a plugin (or modify the theme) to add a jquery header (my dream goal would be something like here: http://www.lfg.co/ ). When using a plugin (headroom.js), I have to specify the element to apply it to. I've tried using #header, header, header.site-header, and header.page-header. Can you suggest the correct HTML element?  Or if you have some solution to make the dream goal happen, I'd appreciate that.  I have the code ready to make the bar, but can't seem to implement it into the site.  I can go into more detail if you need.

3) I've removed the Title and Tagline of the site in the customize menu, but they are still showing up.  I thought I saw this in a post somewhere, but can't find it now.  So a fix for that would be nice.

Sorry I'm listing so many things in one post.  I'm okay with handling them one at a time or through email if you'd prefer.
Thanks in advance,
Gaius

**Comment by mgsisk** [comment]
1. I'm not exactly sure how you're integrating Disqus comments in your site, but the trick would be to pass the Webcomic post ID and not the Page ID (which is probably what it's getting right now). This might require tweaking the Webcomic Homepage template in your setup to manually invoke whatever function outputs the Disqus comments and passing the correct Webcomic post ID.
2. The class you're looking for is `.banner` (see the `header.php` file).
3. There was a bug in the release of Inkblot 4.1 that was causing that setting to be ignored. Should be fixed now (the current version is Inkblot 4.1.3).

**Comment by gaiusjaugustus** [comment]
Thanks for the quick reply.  I've got #s 2 & 3 working now, thanks!  Quick thing about the banner.  It doesn't seem to be aligned center.  I'm cautious to override the inkblot css, since it'll be overwritten when there are updates.  I suppose I could add a custom css plugin.  Do you think this would work?

I'm still struggling with #1 (the Disqus issue), but I'm trying to either find a workaround or work with Disqus.  Another question though.  If I want to link to the latest comic without linking to a "Webcomic homepage", what do I link to?


Thanks again!

**Comment by mgsisk** [comment]
Can you share the code you're using to display Disqus comments on the page? Or are you using a Disqus plugin of some kind? If I can see how you're doing it now I might be able to sort it out.

The [`last_webcomic_link`](https://github.com/mgsisk/webcomic/wiki/last_webcomic_link) template tag will always link to the most latest webcomic post. There's also a widget – [Webcomic] Link – you can use to link to the last (latest) webcomic.

**Comment by gaiusjaugustus** [comment]
I am using the Disqus plugin for Wordpress.  https://wordpress.org/plugins/disqus-comment-system/
