### ISSUE TITLE
Inkblot upgrade, blank index.

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/webcomic#228]
Hi there, 

I just updated Inkblot and I'm using a custom child theme. Now the index is blank and nothing is showing. My site is at http://tdugn.com

**Comment by mgsisk** [comment]
It's… definitely blank. Do any other pages work?

It's nearly impossible to tell what's going on since there's absolutely no output, but there's probably a fatal error somewhere. If your child theme has a `functions.php` file, can you try adding this to the top of it (just inside the opening `<?php`):

```php
error_reporting(~0); ini_set('display_errors', true);
```

That will (hopefully) force some output that reveals where the issue is.

**Comment by CAMorgan** [comment]
All other pages work except the index. I got a fatal error on line 13 of webcomic/home.php. This is the code I have between lines 1 and 34. 


`<?php

/** Webcomic home template.
 * 
 * This is the Webcomic-specific homepage template (used in place of
 * the normal `home.php` or `index.php` when Webcomic is active).
 * The only real difference between this template and the normal
 * template is the inclusion of a webcomic.
 * 
 * @package Inkblot
 * @see github.com/mgsisk/webcomic/wiki/Templates
 */

if ( inkblot_theme_preview() or ( get_theme_mod( 'webcomic_home_hook', true ) and !is_paged() ) ) {
	$webcomics = new WP_Query( array(
		'posts_per_page' => 1,
		'post_type'      => get_theme_mod( 'webcomic_home_collection' ) ? get_theme_mod( 'webcomic_home_collection' ) : get_webcomic_collections(),
		'order'          => get_theme_mod( 'webcomic_home_order', 'DESC' )
	) );
} else {
	$webcomics = false;
}
get_header(); ?>`

**Comment by mgsisk** [comment]
Ah, there it is. The `inkblot_theme_preview()` function was removed in a recent Inkblot update. WordPress now provides it's own function – `is_customize_preview()` – for the same purposes that function used to serve. You'll want to swap out any references to `inkblot_theme_preview()` for `is_customize_preview()`.

**Comment by CAMorgan** [comment]
Figures. Thanks for letting me know! I'll let you know how it goes.

**Comment by CAMorgan** [comment]
All fixed up. Thanks again!
