### ISSUE TITLE
Assign a URL to random_webcomic_navigation?

### ISSUE THREAD

**Issue by kamenliew** [mgsisk/webcomic#229]
Hello mgsisk,

Just wanted to know if it's possible to assign a URL link to the random webcomic nav button? Instead of the random nav button generating random comic pages I would like it to link to the very first page of my storyline which I've designated as my "Intro" page. Alternatively I have also seen some people using it as their "Home" button.

CSS doesn't allow you to link a URL button to a background image and I don't know enough php to write the proper code in my functions.php file without breaking my site. I can't alter the HTML either since there's no HTML file in my wordpress theme directory so I'm at a total loss.

What should I do? Any advice would be much appreciated :)

**Comment by mgsisk** [comment]
Are you using [Inkblot](//github.com/mgsisk/inkblot), or Integration with a different theme?

**Comment by kamenliew** [comment]
Yes! I'm using Inkblot!

**Comment by mgsisk** [comment]
With Inkblot you have a couple of options:

1. The webcomic nabbers are widgetized in the most recent versions of Inkblot, so you *could* just drop a bunch of **[Webcomic] Link** widgets in there and build out the navigation exactly as you'd like.
2. Alternatively, you can find the default navigation links in the `webcomic/image.php`. You'd want to modify lines 22 and 46 to something like:
```php
…
?><a href="http://yourdomain.com/link/to/intro">Link text or image</a><?php
…
```

**Comment by kamenliew** [comment]
Thanks for your reply! Two questions:

1) I've modified image.php as you said and managed to get the link to work but the background-nav-image isn't showing. Is this how you write the code?
...
?><a href="http://yourdomain.com/link/to/intro"><img src="http://yourdomain.com/nav-images</a><?php
...

I tried removing the background-nav-image css styling from the stylesheet.css file in my child-theme folder but it didn't work, bg-nav-img still isn't showing.

2) Has Webcomic-navigation been removed from customizer? I recalled being able to check/ uncheck the top and bottom webcomic navigation from the appearance>customize menu but it seems to have disappeared. I tried original Inkblot (the parent theme of my child theme) but it seems to have disappeared from there too.

Have I disabled it by accident? Coz your idea of using the [Webcomic] Link widget to customize the webcomic nav bar seems like a better alternative :)

**Comment by mgsisk** [comment]
Most Webcomic-specific options – including the option to toggle the navigation bars – are now found under the **Webcomic** section of the customizer.

![screen shot 2015-02-04 at 10 10 47 am](https://cloud.githubusercontent.com/assets/80775/6043530/c97280d8-ac5a-11e4-9cf5-c4597a5081bd.png)

You can customize each navigation bar under the **Widgets** section.

![screen-shot-2015-02-04-at-10 17 55-am](https://cloud.githubusercontent.com/assets/80775/6043586/2646e740-ac5b-11e4-9d85-f0dbbf747453.jpg)

In the Customizer you have to be on a Webcomic page to actually see and customize those widgetized areas. You can also customize them from the **Themes > Widgets** administrative page.

**Comment by kamenliew** [comment]
Thank you so much! I managed to get it to work! All I did was manually change the code in the image.php file :)

I have a final question - I tried dropping the <strong> [Webcomic] Link </strong> widget into the webcomic nav header/ footer but the <strong>'target'</strong> is only set to first, previous, random, next and last.

Is it possible to have an option in that widget that allows us to target a URL instead? In order to do this will it require an extensive amount of php writing?

Thanks again!

**Comment by mgsisk** [comment]
It would take a bit of work to modify **[Webcomic] Link**, but it's probably not even necessary. You can just use a **Text** widget (one of WordPress' default widgets) and drop the link code you want in there, like:

```html
<a href="http://yourdomain.com/url/to/go/to">Link Text</a>
```
Leave the *Title* blank on the widget and it should show up like any other link.

**Comment by kamenliew** [comment]
Ok cool sounds good, thanks again so much for your help.

I've encountered another problem with my webcomic posts.

I noticed that a scroll-bar appears randomly on the side of my webcomic page each time I
A) Try to resize the maximum layout of my page via customizer
B) Try to resize my web-browser (by minimizing it)

The scroll-bar is annoying bcoz it provokes the reader to mess around with it, creating a jittery effect (where the page appears and disappears every time the scroll-bar is dragged) onscreen.

The only way for me to make the scroll-bar disappear is when I resize the layout to a random size (eg. 880px or 840px, but not any numbers in between) via customizer, but it still appears when I try to minimize my browser manually (by dragging the side of the browser window).

Any chance I might be able to remove that scroll-bar on the side permanently or does it have anything to do with the size of my images?

Thanks :)

**Comment by mgsisk** [comment]
Can you provide a link to your site? I can't diagnose this one without seeing it.

**Comment by kamenliew** [comment]
Yeah sure it's at

skyaltar.com

**Comment by kamenliew** [comment]
Hello mgsisk,

Any advice or feedback in regards to my previous question? Thanks!

**Comment by mgsisk** [comment]
Apologies @kamenliew; I haven't been able to replicate your issue in any web browser I've tested. Safari, Firefox, Opera, and Chrome all seem to display properly (I don't have IE to test with, unfortunately).

**Comment by kamenliew** [comment]
Oh really?

So on your browser, you can't see the scroll-bar on the left side of the webcomic?

The scroll-bar appears on Chrome, but in Safari it just appears as this tiny white-space

**Comment by mgsisk** [comment]
Strange. Can you post a screenshot of what you're seeing in Chrome?

**Comment by kamenliew** [comment]
![image](https://cloud.githubusercontent.com/assets/10792012/6175946/0605b308-b34f-11e4-830d-949e4ad902a9.png)

**Comment by kamenliew** [comment]
![image](https://cloud.githubusercontent.com/assets/10792012/6175990/5d2bcd5c-b34f-11e4-9a3d-96666538a1ee.png)

**Comment by kamenliew** [comment]
And when I try to move the scroll-bar up the webcomic completely disappears

**Comment by mgsisk** [comment]
Try adding this to the **Stylesheet** section in the Customizer:

```css
.webcomic-image { overflow: none; }
```

**Comment by kamenliew** [comment]
Hello MGsisk, I tried that but it didn't work.

Have you encountered this issue before?

**Comment by mgsisk** [comment]
Interesting. I've never seen this issue before. It's almost certainly an `overflow` issue, though; try narrowing the rule to:

```css
.post-webcomic .webcomic-image { overflow: none; }
```

**Comment by kamenliew** [comment]
Hmm ... I tried that too, still didn't work.

That's alright MGsisk, I might undo all my CSS/ php coding in my child theme folder (as well as deactivate some of my plugins in the dashboard) and see if the issue still persists after resetting the theme back to default.

I'll report back again soon, thanks for your help and your extensive replies MgSisk, I really appreciate it!
