### ISSUE TITLE
Possible bug with displaying latest comic page (last in stack, not on homepage)

### ISSUE THREAD

**Issue by ashikai** [mgsisk/webcomic#231]
Hello again!

While running through the 'comic reader' section of my site to ensure everything was working correctly, i stumbled upon a very odd bug.

Basically, if you click the NEXT button on the second-newest page, you're redirected to a page where everything gets seriously jumbled. I don't really know how else to explain it, so here is the easiest way to replicate the bug:

----->From the homepage, hit PREVIOUS, then hit NEXT. You'll see the jumbled page.

This jumbling doesn't happen on ANY other page. I should know as I've been through all 500 pages several times just to make sure. It only happens on the NEWEST page...even if you go there through a direct link (today's page http://shamrockcomic.com/pages/v03-c21-cover-3/ ).

I've scoured my code and I cannot for the life of me figure out what's triggering this, which leads me to believe that it could be a bug. Any help with this would be greatly appreciated! \QAQ/

**Comment by mgsisk** [comment]
The issue appears to be with the `position: absolute;` rule on the `.current-webcomic` class (line 269 in `style.css`); removing that corrects the formatting. When `the_webcomic()` is set to link the comic image to a comic (next, previous, etc.) it actually just grabs the image and then runs it through the appropriate navigation template tag. This means that the rendered anchor includes all of the CSS classes that those links typically have, including `current-webcomic` (when you're looking at the current webcomic).

If you need the `position: absolute;` for other current webcomic links, try narrowing it with something like `.comic-nav .current-webcomic`.

**Comment by ashikai** [comment]
....well I feel dumb. I put that on there when I was testing something else and I apparently never took it off. >_>;;

I'll be honest dude, I've never found a plugin/theme guy who responds as quickly, thoroughly and helpfully as you do. I will do my best not to bug the crap out of you with my rusty coding! Thank you so much for your help! QAQ
