### ISSUE TITLE
Missed Schedule?

### ISSUE THREAD

**Issue by ashikai** [mgsisk/webcomic#233]
Two of my comic pages didn't auto-publish and instead got marked with Missed Schedule. It was easy to fix, I just had to go in and click UPDATE and they published themselves, but it's still weird it didn't do it automatically.

What does "Missed Schedule" mean and what triggers it?

**Comment by mgsisk** [comment]
**Missed Schedule** technically means that a post is scheduled to publish (it's post status is `future`) but it's scheduled timestamp has already passed (so it *literally* missed it's scheduled publish time).

The most likely cause is WordPress' own [Cron](http://code.tutsplus.com/articles/insights-into-wp-cron-an-introduction-to-scheduling-tasks-in-wordpress--wp-23119) implementation, which only fires when WordPress is loaded (e.g. anytime someone requests a page on your site). If your site isn't being requested, `WP_Cron` never fires and scheduled tasks (like publishing posts at a future time) don't happen.

There are, apparently, several plugins that try to address this issue, but the best way is probably to just use your server's Cron, [as described here](http://www.trickspanda.com/2014/03/fix-missed-schedule-posts-wordpress/).

**Comment by ashikai** [comment]
Ohhh I see! Thanks so much! I rarely worked with scheduled posts (not patient enough >_>;;) so I wasn't aware of this. Super easy fix though, thank you!
