### ISSUE TITLE
Changing random comic button

### ISSUE THREAD

**Issue by VideoTree** [mgsisk/webcomic#236]
Hello, good afternoon mgsisk, first of all I want to thank you for creating this plugin and Inkblot since I've found both very useful and easy to use when making my webcomic.

Second of all since upgrading both of them to their latest versions I've had some issues.

1.) The header used to be on the center but now I don't know what I should do to center it, I've tried adding: #header > a { text-align: center; } to the stylesheet that shows up on the customization page but it doesn't work.

2.) I had the site configured so when someone selected random page it would take them to the archive instead, it no longer works, I've read that someone has the same issue but I've tried finding the random part on image.php and haven't been able to find it. What can I do?

I was confused between image.php and webcomic/image.php, browsing the second I can find the

random_webcomic_link('%link', get_theme_mod('random_webcomic_image', false) ? sprintf('%s', get_theme_mod('random_webcomic_image'), __('∞', 'inkblot')) : '');

But unlike in the past which was

<?php random_webcomic_link( '%link', get_theme_mod( 'random_webcomic_image' ) ? sprintf( '%s', get_theme_mod( 'random_webcomic_image' ), __( '∞', 'inkblot' ) ) : '' ); ?>

I can't just substitute it with <a href=" since it give me an error that says that a < was found.

Thank you, I hope you have a nice day.

EDIT:
Managed to fix the header issue by changing #header > a { text-align: center; } to .banner > a { text-align: center; }.

The only issue remaining is the random comic one

EDIT:
Managed to change the random comic button, apologies for starting this.

**Comment by VideoTree** [comment]
I was confused between image.php and webcomic/image.php, browsing the second I can find the

random_webcomic_link('%link', get_theme_mod('random_webcomic_image', false) ? sprintf('<img src="%s" alt="%s">', get_theme_mod('random_webcomic_image'), __('&infin;', 'inkblot')) : '');

But unlike in the past which was

<?php random_webcomic_link( '%link', get_theme_mod( 'random_webcomic_image' ) ? sprintf( '<img src="%s" alt="%s">', get_theme_mod( 'random_webcomic_image' ), __( '&infin;', 'inkblot' ) ) : '' ); ?>

I can't just substitute it with <a href="http://yourdomain.com/link/to/intro">Link text or image</a> since it give me an error

**Comment by mgsisk** [comment]
No problem VideoTree; apologies for not being able to respond until you'd already figured it out!
