### ISSUE TITLE
Removing random button and fixing comic descriptions

### ISSUE THREAD

**Issue by Anonimicon** [mgsisk/webcomic#238]
Hey guys, I'm having trouble with my random button on my sites lighthouse.nutmegnautilus.com and denver.nutmegnautilus,com. Since both follow a storyline, I have no need for the random button. However, whenever I remove it in the image attachment template, it breaks the navigation system. Is there a way to remove the random button without breaking the navigation? Removing it also messes up the arrows -- they align left. i want them to be centered with each button having an equal distance from eachother.

I'm also having issues with the descriptions for my comic. For some reason, whenever I navigate, the comment from the page I started on keeps appearing on the bottom. I have some sensitive material in my comic and I want people to be able to read the warning at the bottom. But the only way I can get the right description to appear below my comic is by refreshing the page. Is there a fix for this too?

EDIT: I tried to use the widget to make the navigation bar, but it was aligned left and then it proceeded to break my navigation. I can't use it at all, now. How do I fix it?

EDIT2: For some reason after I turned off dynamic comic page loading, my comic pages shrunk down from 1200x600 to less than half that size. How do I fix that?

**Comment by mgsisk** [comment]
For the navigation, try removing the random link (as you were) and then add this to your theme style.css file:

.post-webcomic nav a {width: 25%}

That should get them spaced properly. For the second issue, try disabling Dynamic navigation on the Webcomic settings page.

Not sure about the image resizing… you may want to double check Inkblot's Customizer settings. By default, webcomic images will adjust their size based on the current width of your site. You may just need to adjust Inkblot's Maximum Width and Minimum Width (set them to the same width if you want a fixed-width site).

**Comment by Anonimicon** [comment]
Thank you so much!! The random button's gone now :D Can I ask about a few more things? I'm struggling with the wrapper on my site. I have it set to a percent width (like 43%), but when it loads on a mobile, the width makes the comic look really small (because its only taking up 43% of the already tiny space). Is there a way that I can wrap the light blue page so it doesn't appear on the sides of my comic pages without it making it look bad on a phone? Also, I'm struggling with the "home, about, archive, etc" pages on the phone. Is there a way to code it so it appears as a drop-down menu on the phone? They're sort of stacking unattractively.  Thanks!!

**Comment by mgsisk** [comment]
It might be easier to use the Customizer to handle the theme width and responsive menu. You can set a minimum and maximum width for the layout (so that it flexes with the viewport size), and if you set a **responsive width** Inkblot will auto-adjust the site when it hits the responsive width (or lower) for smaller screens (e.g. converting the normal site menu into a dropdown, for example).

**Comment by Anonimicon** [comment]
Thank you!! I really appreciate it. That fixed it right away.
