### ISSUE TITLE
Slug not updating on first "untitled-comic" collection

### ISSUE THREAD

**Issue by ImageMagician** [mgsisk/webcomic#239]
I have changed the title and slug of the first collection to my own settings, but the slug will not update. It remains as "untitled-comic".

I have deactivated the plugin and restarted fresh, making sure that I don't do anything until I change the settings, but it still won't change from the default. Is there something I can do to rectify this? 

I'm running WP 4.1.1

**Comment by mgsisk** [comment]
Thanks for reporting this @ImageMagician. I think the settings may be a little confusing here; the **slug** on the collection settings page isn't actually the text used in your site URL's. I don't actually remember *what* – if anything – the slug is used for by default. I'll need to review what that's actually used for, and if it would make sense to either remove it or merge it with the *actual* URL setting.

What you probably want to change are the settings under **Permalinks**. The four options there control the text in your site URL's.

**Comment by ImageMagician** [comment]
Thanks, mgsisk. However, changing the permalinks setting for the site doesn't change the URL path for my comic. Right now it comes out like this "domain.com/untitled-webcomic/". I want the URL to read like this "domain.com/mycomictitle". I can't seem to change the "untitled webcomic". If I create a new webcomic collection, THAT slug/url works fine.

**Comment by mgsisk** [comment]
Apologies, I may not have been clear: Webcomic has it's own Permalinks settings on the collection settings page, which are entirely separate from (though tangentially related to) the site Permalink settings. There are four of them – for archives, webcomic pages, storylines, and characters – which control the various Webcomic-related URL's on your site.

**Comment by ImageMagician** [comment]
Oh! Gotcha! I was able to change the Permalinks on the individual webcomic settings and it works now. Thank you!
