### ISSUE TITLE
Comics get posted twice

### ISSUE THREAD

**Issue by Mastara** [mgsisk/webcomic#242]
Hello everyone!
I am using webcomics with Inkbot and all my comic pages seem to double post. 
The comic plage loads between the navigation bars, and then it loads again just underneath it (non navigable this time)(as if it was a regular wordpress post?).
As far as I can tell, it's the same problem as stated here https://github.com/mgsisk/webcomic/issues/111
It's just that turning off integrate (and all the other options) doesn't solve it. It also carries to other themes.
thank you for your help!

**Comment by Mastara** [comment]
this is the (test) website http://test-webcomics.mereledeaur.ro/

**Comment by Mastara** [comment]
Update. I think I fixed it. After uploading the image from Media library, I deleted the image in the editable-text-area - this didn't seem to delete in image which was still visible in the webcomic media on the right side.  Disclaimer - I know very little about Wordpress, sorry if I get the names wrong...

**Comment by mgsisk** [comment]
No problem Mastara. As you discovered, you don't have to actually *insert* the image into the post; Webcomic will display it anyway. You can just delete the image after inserting it, or click the X on the media popup to dismiss it instead of the insert button.
