### ISSUE TITLE
Second Image Above Header

### ISSUE THREAD

**Issue by Llaucian** [mgsisk/webcomic#244]
Hello,  I am sort of new to wordpress and am having an issue with the integration of webcomic with the theme I'm working with (raindrops). Whenever I post a new comic to the site, it puts one copy of it at the top of my header on my home page and then another underneath of it. This only applies to the home page. It doesn't duplicate it on other pages. Also I have made certain that I am not putting the image into the post, so that's not the reason it's duplicating. Here's a zoomed out image of what is occurring, but if you need me to post some of the theme's code, just let me know how and I can grab it.  Thanks!

![problem](https://cloud.githubusercontent.com/assets/4218520/7300259/3260225e-e9a9-11e4-8c98-fa8939f78838.png)

**Comment by mgsisk** [comment]
Apologies for the trouble @Llaucian. It looks like Raindrops is running a loop in the site `<head>`. There's really no way to differentiate a loop in the site `head` from the standard loop, so Webcomic is attempting to integrate on both, causing the double-rendering.

I'm not sure what the block of code is actually doing, but if you comment out lines 3024–3057 in `functions.php` that will disable the `head` loop and prevent the double-integration.

**Comment by Llaucian** [comment]
I tried commenting out lines 3024-3057 in functions.php using DreamWeaver, but that has ended up giving me a 500 Internal Server Error. Is it possible that maybe I commented out the wrong code?  The code I commented out was: 

						/*the_post();
						$web_fonts = get_post_meta( $post->ID, '_web_fonts_link_element', true );

						if ( isset( $web_fonts ) && !empty( $web_fonts ) ) {

							$web_fonts_each_array = explode("\n", $web_fonts);

							foreach( $web_fonts_each_array as $web_fonts_each ) {
								$result = str_replace( array( $web_fonts_each,"\n\n"), array('',"\n"), $result );
								$result .= $web_fonts_each ."\n";
							}
						}

						$web_fonts_style = get_post_meta( $post->ID, '_web_fonts_styles', true );


						if ( isset( $web_fonts_style ) && !empty( $web_fonts_style ) ) {

							$web_fonts_style_each_array = explode("\n", $web_fonts_style );

							foreach( $web_fonts_style_each_array as $web_fonts_style_each ) {
								$result_indv = str_replace( array( $web_fonts_style_each,"\n\n"), array('',"\n"), $result_indv );
								$result_indv .= $web_fonts_style_each ."\n";
							}
						}

						$collections = get_post_meta( $post->ID, 'css', true );
						$collections .= get_post_meta( $post->ID, '_css', true );
						if ( !empty( $collections ) ) {
							$result_indv .= preg_replace_callback( '![^}]+{[^}]+}!siu', 'raindrops_css_add_id', $collections );
						}
					}
					rewind_posts();
*/


Thanks again for your help. It's really appreciated. I'm sorry I'm such a novice at this.

**Comment by mgsisk** [comment]
Sorry @Llaucian; in the copy I downloaded, 3024 is actually the line just above the `the_post();` bit:

```php
while ( have_posts() ) {
```
You'll want to comment out that entire `while` block (everything from `while` to `rewind_posts();`).

**Comment by Llaucian** [comment]
That worked perfectly! Thank you so much for your time and this plugin.
