### ISSUE TITLE
Does Storyline dropdown tag work in WP 4.2?

### ISSUE THREAD

**Issue by lhornsby** [mgsisk/webcomic#245]
I usually test bigger WP updates locally before updating on my comic's live site. I just updated to 4.2 locally, and the only adverse change I could see is that the select box that gives the dropdown links to storylines has disappeared. I don't get any debug information, the code just doesn't generate anything. What I have that was working locally and is still on my live comic's site is this:
<?php webcomic_dropdown_storylines(
	array(
		'collection' => 'webcomic1',
		'show_count' => 'true',
		'target' => 'first',
		'show_option_all' => '- Pick a Chapter -'
));?>

Not sure if there's something on my end or if it's something to add into the next update for the Webcomic plugin, so I thought I'd bring it up.

**Comment by Kuriousity** [comment]
All my storyline dropdown menus have vanished as well

**Comment by lhornsby** [comment]
I guess it's not just my local install then. Since WP just had a security release, I went ahead and updated on my live site and can confirm it also disappeared there as well.

**Comment by mgsisk** [comment]
The issue appears to be with Webcomic using the `name` argument in that function. WordPress' `get_terms` function – which Webcomic is using internally – expects `name` to contain the name of a term you're looking for, which is *not* what Webcomic is using it for. This results in no terms being found, and no output being generated.

I can't find any info to suggest that this is new to 4.2, but it's definitely causing issues now. There's no simple fix for this, unfortunately, as it requires updating several functions. I'll try to get a fix pushed to the repository and the plugin directory tomorrow.

**Comment by mgsisk** [comment]
Thanks again for reporting this @lhornsby and @Kuriousity. I have a fix, and it should be available tomorrow afternoon. Apologies for the delay.

**Comment by lhornsby** [comment]
Thanks for finding a solution, @mgsisk ! Looking forward to the fix.

**Comment by mgsisk** [comment]
4.3.1 – which includes the fix for this issue – should be in the Plugin Directory shortly.
