### ISSUE TITLE
All posts are orphaned?/Bulk attaching

### ISSUE THREAD

**Issue by Narrowedeyes** [mgsisk/webcomic#246]
Please help!
I'm sorry if i'm in the wrong channel for this, but i clicked on the irreversible transfer/upgrade option and kinda screwed myself up. I want to use this plugin with Inkblot instead of my previous Comic Easel, but i have about 150 pages now that i have to reattach to all these new categories and slugs.

So, 2 problems:

I can't seem to figure out how to actually put the comic in the comic/content panel. A really base-level problem, i know, but anything i upload to the Webcomic Media panel just shows up in the description. Because of this, all my posts are orphaned. 

Further, is there a way for me to use the attacher to put up my pages in bulk? Otherwise i'll be here for hours reuploading.

Thanks, if you can help. My comic is my life, and i'm panicked when my site is down.

**Comment by mgsisk** [comment]
For posterity, I replied to @Narrowedeyes on [the WordPress support forum](https://wordpress.org/support/topic/cant-attach-imagesbulk-attaching?replies=1#post-6954511).
