### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by faoliveira** [mgsisk/webcomic#247]
I found that the plugin has the i18n folder, I did the translation and put the name of the po file of the language (pt_BR), but din't worked. The language support is already activated?

**Comment by mgsisk** [comment]
It should be, but I think you're the first person to actually try it out so it's entirely possible something is broken and it just hasn't been found yet. Can you share your translation (either here or in an email to me) so I can try it out on my dev box?

**Comment by faoliveira** [comment]
Hi! I made a pull request with the translation. It's not complete yet
