### ISSUE TITLE
Problems with titles and body text

### ISSUE THREAD

**Issue by mywerewolf** [mgsisk/webcomic#251]
I want a title and the option of some text underneath my comics. The titles and body text for my posts are not updating. Instead, it just displays the most recent title on all of the pages. I've uninstalled and reinstalled several times, so I don't know what's going on.

**Comment by mgsisk** [comment]
Without seeing it, I'd guess **Dynamic navigation** is to blame. Disabling dynamic navigation–if it's on–should resolve the issue.

**Comment by mywerewolf** [comment]
Where is the setting for dynamic navigation? I haven't changed it so it's
odd that this would be the default.



On Jun 3, 2015, at 5:14 AM, Michael Sisk <notifications@github.com> wrote:

Without seeing it, I'd guess *Dynamic navigation* is to blame. Disabling
dynamic navigation–if it's on–should resolve the issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/mgsisk/webcomic/issues/251#issuecomment-108352775>.

**Comment by mgsisk** [comment]
Dynamic navigation is on the **Settings > Webcomic** page. It's actually **not** on by default, but that's usually the issue when something like this happens (technically it's a dynamic navigation and Inkblot issue).

It's impossible for me to know what the actual issue is without seeing your site, unfortunately.

**Comment by mywerewolf** [comment]
I turned that off and it’s still just displaying the most current title/text. If I load the homepage, it will keep “title 2” on both pages. If I load the other page first, it will display “title 1” on both pages.

http://numinadesign.com/mywerewolf/
