### ISSUE TITLE
Comic Not Centered

### ISSUE THREAD

**Issue by Llaucian** [mgsisk/webcomic#252]
Hi again, 

I think we're just one step away from having everything the way we want it on our website. The only problem, and it's a fairly minor one to us, is that the main comic is not centered. It's just pushed way to the left. I imagine this has something to do with the style.css, but I haven't found anything. We're using the raindrop theme and here is a link to our website www.hinge-studios.com.

Thanks, 
Jason

**Comment by Mihari** [comment]
Adding this CSS should solve the problem for you: 

```CSS
div.webcomic-image { text-align: center; }
```

**Comment by Llaucian** [comment]
Thanks, a simple and effective solution!
