### ISSUE TITLE
Navigation doesn't update text accompanying webcomic

### ISSUE THREAD

**Issue by RobCottingham** [mgsisk/webcomic#254]
I'm using Inkblot and Webcomic (latest version of each). When visitors use the navigation links, the image updates, but the accompanying text doesn't. Is there a setting I'm missing?

Thanks!

**Comment by Mihari** [comment]
Do you have ```Dynamic webcomic navigation``` enabled in the ```Settings -> Webcomic``` section? If so that is the likely culprit, I haven't looked in a while, bu I do believe that only the webcomic image is stored within the dynamic nav loop.

**Comment by RobCottingham** [comment]
Well, dang! That fixed it — thanks so much for the tip!

Rob Cottingham
m. 778-995-7622
www.socialsignal.com
www.robcottingham.ca
