### ISSUE TITLE
Customizer Section for Archive(s)

### ISSUE THREAD

**Issue by Mihari** [mgsisk/webcomic#259]
Since the archive generation is all done from basically a single array; would it be possible to add a section in the WordPress customizer that lets end users input what they want in what order they want with perhaps basic format editing, like alignment (left, right, center) or multiple columns, etc.

As it stands, currently, I have an entire multi-site running off a single instance of a lightly modified inkblot and child theme, and the customizer and custom.css changes handle all the rest making each one their own. However you can not have separate archive templates as it currently is.

If you get my meaning?

**Comment by vandalk** [comment]
Maybe you can make multiple archive templates inside a single php template file by using some "if"s to identify each site by their blog name or home url?

maybe something like:
```php
if (bloginfo(name)=="Site Name 1") {
//All the code for the archive for this particular site
} elseif (bloginfo(name)=="Site Name 2"){
//And so on...
```

Then you could also give unique ids or classes for each, as needed, so you can style them differently on custom.css.

I don't know if this would really work, just had this idea by reading your issue.
