### ISSUE TITLE
increase size of nav bar & change page order

### ISSUE THREAD

**Issue by cartoonjazz** [mgsisk/webcomic#261]
Hi I'm using "Portfolio Gallery" Theme. Everything looks great except the nav bar is tiny . I would like to have it look the way it looks in inkblot. Can you provide some help re editing this theme? an example is at http://www.variouscomics.com/a-viikings-story/a-vikings-story/

Also after pages have been assigned through the webcomic generator how do you change their order in the webcomic?
https://wordpress.org/plugins/webcomic/

**Comment by ykyu** [comment]
Your navbar actually looks [pretty huge](http://i.share.pho.to/21b584c0_o.png) to me? However, you can adjust the font size in the nav bar via your CSS by adding **font-size: 35px** or whatever value you'd like, to **.banner nav a**, like so:

```
.banner nav a
{
color: #767676;
display: block;
line-height: 2.4;
padding: 0 1rem;
white-space: pre;
font-size: 35px;
}
```
You should be able to change the order of webcomics in a collection by editing the publication date of individual webcomics.
