### ISSUE TITLE
Webcomic navigation to URL instead of next comic

### ISSUE THREAD

**Issue by dglisson** [mgsisk/webcomic#264]
Hi, I was wondering if there is any way to change the settings on a particular webcomic so that the "next" nav button leads to a URL and not the next comic?

The reason is, I would like to set it up so that the last page of a particular storyline leads to a landing page URL, that URL will then have a link to the first page of the next storyline.

Is it possible to break things up in the same collection this way? What would I have to do to accomplish this?

**Comment by ykyu** [comment]
Hm. Messing with the next/previous data for webcomic pages on a single page basis would be messy and complicated, I think. No real elegant way to do it without shoehorning in a lot of unnecessary components, imo. It's much easier to just include a link from the commentary on the page, perhaps in a bold heading if you think people might miss it.
