### ISSUE TITLE
Sidebar disappears when using a separate child theme on comic #2

### ISSUE THREAD

**Issue by sailorptah** [mgsisk/webcomic#268]
I've set up my installation of Webcomic to run a second comic. Comic #1 uses an Inkblot child theme, and I'd like Comic #2 to have a different color scheme, which means using a different child theme...

Except that the Primary Sidebar area disappears in Comic #2 when I switch themes. And it's not something in the new CSS affecting how it displays, because at this point child theme #2 is identical to child theme #1 in all but name.

A typical page of Comic #1, with the sidebar (search, comments, etc) intact:
http://leifandthorn.com/comic/fish-story-541/

The CSS for child theme #1:
http://leifandthorn.com/wp-content/themes/leifthorn/style.css?ver=4.4.3

Test page of Comic #2, no sidebar:
http://leifandthorn.com/leif-thorn-after-dark/stancziaimri-these-costumes-are-tacky-but/

And, for completeness' sake, the CSS for child theme #2:
http://leifandthorn.com/wp-content/themes/secondary/style.css?ver=4.4.3

(The header image has also conspicuously gone missing in child theme #2, but I'm going to be replacing it anyway, and in that case I know how to make it happen. It's only the sidebar I can't figure out.)

**Comment by mgsisk** [comment]
Try adding this to the `functions.php` file in the child theme for Comic 2:

```php
function content_override() {
	return 'two-column content-right';
}

add_filter('theme_mod_content', 'content_override');
```

**Comment by sailorptah** [comment]
Worked perfectly, thank you!

I don't have separate functions.php files for the child themes, so it went in the main one for Inkblot. Is this something you can build in by default for future versions, or should I just make a note to re-add it every time the theme updates?
