### ISSUE TITLE
"Start of storyline" navigation button

### ISSUE THREAD

**Issue by katedrawscomics** [mgsisk/webcomic#270]
Hi, is it possible to have a navigation button underneath the current ones that would take you back to the start of the storyline the current page is in? Say, if you're reading a page from storyline X and you click this link it'll take you right back to the start of storyline X, and when you're reading a page from storyline Y the link would take you back to the start of storyline Y.

Thanks!

**Comment by Mihari** [comment]
There is a widget you can use that will do the feature you're asking about if I'm understanding correctly, it's the [Webcomic] Storyline Link

**Comment by katedrawscomics** [comment]
Thanks- That's nearly it, but I can't seem to make it show the current storyline- my choices are the previous one, the next one, the first one, etc, none of which are the current one!

**Comment by Mihari** [comment]
This shortcode can get you the current storyline:
`[the_webcomic_storylines]`

**Comment by katedrawscomics** [comment]
Ah, that's great! Unfortunately, if I add it into the navigation footer/header, it removes the arrows that are already there..

**Comment by Mihari** [comment]
By default if you do add any navigation through the use of widgets it will remove the defaults, but you can simply add them back by putting the widgets that generate the same links. Those are the "[Webcomic] Link" widget, I believe it is.

All the tags and shortcodes and more are listed in the wiki here on github, but for shortcodes specifically here you go: [Shortcodes](https://github.com/mgsisk/webcomic/wiki/Template-Tags-and-Shortcodes)
