### ISSUE TITLE
Updated Inkblot theme and sidebars have vanished

### ISSUE THREAD

**Issue by katedrawscomics** [mgsisk/webcomic#271]
Hi, still got all of my content in my usual primary sidebar, and set the layout to content on left, 1 sidebar, but it seems to just be stacking it up underneath the comic, for some reason, like so- http://www.widdershinscomic.com/ all of those ads and banners under the content are meant to be at the side.

Edit: A friend fixed it, I have no idea how, I hate CSS a lot

**Comment by mgsisk** [comment]
Apologies for the trouble, @katedrawscomics.
