### ISSUE TITLE
Wordpress Updates messed up my layout.

### ISSUE THREAD

**Issue by theoryofeverything** [mgsisk/webcomic#274]
Hi,

So this is an issue I haven't had time to touch, [www.theoryofeverythingcomic.com](http://www.theoryofeverythingcomics.com) is supposed to have this layout (the purple bar is an ad banner).

![webpage_01](https://cloud.githubusercontent.com/assets/3366809/16891643/f8e4c870-4ab1-11e6-9079-153d2f4231a8.jpg)

My provider updated WP and the layout changed. I have no idea where to start to fix this. Maybe you could take a look. Hopefully its an easy fix.

**Comment by mgsisk** [comment]
Apologies for the trouble, @theoryofeverything. It looks there's an error that's causing the Webcomic-specific templates to stop rendering after the opening `<footer class="post-footer">` element. Can you post a copy of your themes `webcomic/content.php` file?

**Comment by theoryofeverything** [comment]
`<?php`
`/** Generic webcomic content template.`
` * `
` * This is the generic content template for webcomics, mostly used`
` * on archive pages. See webcomic/content-single.php for the`
` * standard, full-size webcomic display with navigation.`
` * `
` * @package Archimedes`
` */`
`?>`
`<div class="post-webcomic">`
		
`	<div class="webcomic-img">`
		
`		<?php the_webcomic( 'large', 'self' ); ?>`
		
`	</div>`
	
`</div>`

**Comment by theoryofeverything** [comment]
Hey Michael,

Do you see anything in webcomic/content.php ?

At least point me in the right direction to fix this.

**Comment by mgsisk** [comment]
Apologies @theoryofeverything; I thought I'd replied via email, but apparently not. =/

I believe the problem is actually in `single-content.php`. Line 34 calls `the_webcomic_collection()`, but that template tag was deprecated awhile ago and eventually removed. Try changing it to `the_webcomic_collections()` (with an `s`).
