### ISSUE TITLE
Post settings inconsistent 

### ISSUE THREAD

**Issue by MrMMorris** [mgsisk/webcomic#275]
so I am trying to remove the attachment image at the bottom of posts, and I noticed that the state of the page when you first navigate to it and when you refresh it, are different.

For example:
1. Go to http://westsevencomic.net/
2. click the next arrow on the navigation
3. scroll to the bottom and see there is no comments or attachment image
4. refresh page and see that there is now comments and an attachment image

My questions: Why is this happening? How can I fix it so that there **are** comments and **aren't** attachment images every time the page is refreshed?

Thanks!

**Comment by mgsisk** [comment]
From the looks of it, this is probably related to **Dynamic Navigation**. Turning off Dynamic Navigation on the Settings > Webcomic page should correct the issue.
