### ISSUE TITLE
Navigation Menubar

### ISSUE THREAD

**Issue by 3D-Printed-Props** [mgsisk/webcomic#279]
Hello,
New to the plugin. Site still underway but the navigation is not displaying correctly at all. I used the media library to create the webcomic posts but all I get is an infinity symbol and the nav arrows are very close together. How would I fix this. I would also like to change the arrows to graphics. The link is below. Thanks.

http://www.pixelstrips.com/

**Comment by Mihari** [comment]
Once in the Dashboard navigate to Appearance -> Widgets -> Look for "Webcomic Navigation Header/Footer" in there you can use the widget "Webcomic [Link]" in there to place the custom links you desire, keep in mind if you put anything into this widget area it will remove all current nav links for that area.

**Comment by kevinvolo** [comment]
I just did that and the name is now there, but the links for next, Prev and all that are to close and once past page 1 the name turns into an infinity symbol.
