### ISSUE TITLE
Remove link on images

### ISSUE THREAD

**Issue by duanewilson** [mgsisk/webcomic#281]
Hi

Currently on the site the comic has a link to itself - for instance here http://rocketmummy.com/comics/ the images click goes to the post : http://rocketmummy.com/comics/the-mummys-sabbatical/week-19-a-critical-eye/ would like to remove that link because it messes with scrolling on iPhone, the tap event is messed up and counts a scroll gesture as a link click. I just can't figure out where to go to remove that link :D

**Comment by Mihari** [comment]
Appearance -> Customize -> Webcomic -> Navigation -> "Webcomic attachments link to" : Nothing
