### ISSUE TITLE
Storyline Dropdown: Not Showing Up On My Main Comic Page

### ISSUE THREAD

**Issue by FINGL0NGER** [mgsisk/webcomic#288]
I've got a storyline dropdown menu that doesn't show up on my comic's front page. I have to navigate to a different webcomic (i.e. any URL that displays a webcomic slug) and only then does the dropdown menu show. However, if I load a _collection_ dropdown menu, that displays just fine in either case.

So here, only the collection dropdown shows:
http://test.red-oasis.com/comic

But here, both show:
http://test.red-oasis.com/comic/metropolis_022

I suppose I could just use the collection dropdown since it displays when I want it to, but I'd rather use the storyline one. Is there any way to fix this?

**Comment by mgsisk** [comment]
Not sure if you addressed this or not, but you may need to specify a Collection for the Storyline Dropdown. Webcomic can't determine the "current" collection on the homepage, so it's always best to specify a Collection if you're using it on the homepage.

**Comment by FINGL0NGER** [comment]
That appears to have done it. Thank you!
