### ISSUE TITLE
Dropdowns Not Working

### ISSUE THREAD

**Issue by FINGL0NGER** [mgsisk/webcomic#289]
When I load up any given page of my webcomic, the dropdown menu (whether it's a storyline dropdown or a collection dropdown) works fine. But if I start using the navigation buttons (next, previous, first, etc), the dropdown menu stops working. I've tried it on multiple computers and with multiple browsers, but the problem is still there.

Here, load this page then use the nav buttons to go to the next or previous page, then try and use either dropdown menu.
http://test.red-oasis.com/comic/metropolis_009

**Comment by FINGL0NGER** [comment]
After some more troubleshooting, it seems this problem is caused by dynamic navigation. Turning that feature off corrects the problem, but I'd rather keep it on. Is there any way to get the dropdown menu to work with dynamic navigation?

**Comment by mgsisk** [comment]
Thanks for bringing this to my attention, @FINGL0NGER; pretty sure this is a bug of some kind. I'm – very, painfully slowly – trying to finish up a new release of Webcomic, but will see if I can find a temporary fix for you.

**Comment by FINGL0NGER** [comment]
Thanks.
