### ISSUE TITLE
says webcomic not installed when it is

### ISSUE THREAD

**Issue by tehandeh** [mgsisk/webcomic#293]
basically out of the blue wordpress just started saying webcomic wasnt installed or activated when its clearly activated. i'm using inkblot theme if it matters. not sure if this is due to the last wordpress update or not.

**Comment by mgsisk** [comment]
Strange… I'm not aware of any issues with recent versions of WordPress. Can you confirm that the plugin exists at `wp-content/webcomic` and that – at the very least – a `webcomic.php` file exists?

**Comment by tehandeh** [comment]
it only appears in wp-content/plugins/webcomic    is that a problem?

**Comment by mgsisk** [comment]
Nope, sorry; that's actually the correct location (it's been a long day…).

So the plugin and all it's files are definitely there, but WordPress isn't showing it in the Plugin's list? Or it's in the plugin list and activated, but none of the related Webcomic pages (collection post lists, Settings > Webcomic page, etc.) are showing up in the admin dashboard?

**Comment by tehandeh** [comment]
its activated, settings shows up but in page editor when i select one of the webcomic templates it says webcomic isnt installed or activated

**Comment by mgsisk** [comment]
Ah, ok; I think I understand now. It sounds like this is actually an Inkblot issue, where you're selecting one of Inkblot's Webcomic-specific templates but it thinks Webcomic isn't even installed. Interesting; I'll try to look into this tonight. My guess is it's a really stupid bug in Inkblot that's causing the issue.

**Comment by mgsisk** [comment]
Can't seem to replicate this on my dev box, but it sounds like Inkblot's `functions.php` might be loading before Webcomic somehow, at least when you're editing a page.

If Webcomic is definitely installed and activated, you can try opening up `/inkblot/-/php/tags.php` and either changing the `webcomic()` function so that it always returns `true`; that should force all of Inkblot's Webcomic-related features – including page template options – to work.

**Comment by tehandeh** [comment]
this never did work for me.  and now I did the latest upgrade and when I went to activate I got this error 

> Plugin could not be activated because it triggered a fatal error.
> 
> Fatal error: Cannot redeclare class Webcomic in /home1/pinkard/public_html/teabeer.tehandeh.com/wp-content/plugins/webcomic-4.3.3/webcomic.php on line 34

**Comment by mgsisk** [comment]
Thanks for the update @tehandeh. It looks like the newest version is being put in directory called `webcomic-4.3.3`, which is not correct. Did you update the through WordPress (e.g. via the Dashboard > Updates page or the Plugins page) or manually?

**Comment by tehandeh** [comment]
i did it via the dash

**Comment by mgsisk** [comment]
Hm… that is super weird. Would you mind if I took a look at your site directly? The update issue definitely shouldn't be happening, and I'm not really sure why Inkblot is flipping out either.

If you like, setup an admin account for me on your site (please don't give me your login information) and email the details to me at help@mgsisk.com

**Comment by tehandeh** [comment]
no probs. email has been sent!

**Comment by mgsisk** [comment]
Thanks @tehandeh. It looks like Webcomic 4.3.3 got installed ok. As a temporary fix for the template options issue, I updated Webcomic's main `webcomic.php` file and added a `webcomic()` function there that always returns `true`.

Still trying to figure out exactly what's causing `webcomic()` to return `false`… it might be related to the Inkblot child theme, but it *should* work based on how everything is setup…

**Comment by tehandeh** [comment]
thanks so much! I originally was using inkblot then tried Archimedes and finally my own child theme.. it looked at first to get, but then the error would return within the hour. which was weird cuz I hadn't added anything new when it happened
