### ISSUE TITLE
Error in admin-meta.js

### ISSUE THREAD

**Issue by wartman** [mgsisk/webcomic#296]
Looks like the closing `} );` is missing on line 52 in admin-meta.js. I had to add it manually when I updated to 4.4. Seems to work fine otherwise!

**Comment by mgsisk** [comment]
Oops; thanks for catching that. Will push an update in a bit.

**Comment by mgsisk** [comment]
Thanks again, @wartman; that's what I get for trying to make updates. v4.4.1 should be live in a few moments on the plugin directory with the fix.
