### ISSUE TITLE
Child theme unexpected PHP debug output

### ISSUE THREAD

**Issue by Mastara** [mgsisk/webcomic#298]
Again, this might be just me being ignorant.
When Child Theme Configurator Plughin analyzes the theme, it comes up with 
The theme "Inkblot" generated unexpected PHP debug output.
Notice:  Undefined index: fields in wp-content/plugins/webcomic/webcomic.php on line 1527
(and if I go ahead and create a child theme it claims not to find the webcomics plugin).
Since I only have a vague idea about how child themes work (but the internet advised me to make one, so...), this might be my fault. Just thought maybe it is worth mentioning...

**Comment by mgsisk** [comment]
Thanks for the heads up @Mastara. This is almost certainly a bug in Webcomic; v5.0.0 should address this, though.
