### ISSUE TITLE
Elementor and Comic on Front page

### ISSUE THREAD

**Issue by tigandrea5** [mgsisk/webcomic#299]
I am currently using the GeneratePress theme and using Elementor to help me customize the them. I had comic press on there which works great with this theme but I am having issues with the comic appears on the front home page and I do not know how to remove this. 

I included an image and used sock images while I was working on the layout. 

![issue pic 1](https://user-images.githubusercontent.com/34611830/34075447-5c2b547c-e295-11e7-866e-d0e4aadd449c.JPG)

![picture pic 2](https://user-images.githubusercontent.com/34611830/34075451-64d27b6e-e295-11e7-8ea4-6f106e6d82b6.JPG)

**Comment by mgsisk** [comment]
Apologies for the late response @tigandrea5; if you're still working through this, can you provide a link to your site?

**Comment by kav-p** [comment]
Hello Mike! While waiting for OP to get back to you, I am encountering the same problem. Here is a link to my web site: http://www.kav-p.com

**Comment by mgsisk** [comment]
Thanks @kav-p! I think I see what's going on now. What you'll want to do is copy the `/wp-content/plugins/webcomic/php/-/integrate/loop_start.php` file into a `webcomic` directory inside your active theme (so you should end up with a `/wp-content/themes/illustratr/webcomic/loop_start.php` file). Inside that file, line 35 should look like this:

```php
<?php if ( is_front_page() ) : ?>
```
and you'll want to change it to this:
```php
<?php if ( false ) : ?>
```
This will prevent comics from showing up on the homepage when using Webcomic 4's integrate option.

**Comment by kav-p** [comment]
Hello Michael,

Thank you so much for the swift response. This has worked brilliantly!

Really looking forward to Webcomic 5, by the way! Any release date in mind?


Regards,
Kav

**Comment by kav-p** [comment]
Actually, I have one more issue I wonder if you could have a look at:

Looking at the first comic here
<http://kav-p.com/emvok/1-the-uglee-beginning/>, there is the appropriate
description and transcript, but clicking to go to the next comic, the
description and transcript do not change with the comic. Is there something
I'm overlooking?

**Comment by mgsisk** [comment]
Thanks! With luck, Webcomic 5 will show up in the WordPress plugin directory yet today. If you’re feeling brave you can download it from GotHub right now, though; the *src* directory is the actual plugin (just rename it to *webcomic* and throw it in your plugins directory).

The other problem your having may be related to dynamic comic navigation. Turn that off on the Settingd > Webcomic page should do the trick.
