### ISSUE TITLE
Infinite Scroll is the Wrong Order

### ISSUE THREAD

**Issue by pixel-prism** [mgsisk/webcomic#308]
### Expected Behavior
So, I created a new page with a Webcomic Infinite Scroll template on my site (http://cvilbrandt.naiya.org/new-readers). I intend to have an infinite scroll of the archive for people to scroll through, from beginning to end.

All the comics in the archive were added via the Webcomic Generator, but the Generator also added them in reverse chronological order. I had to go through and manually update the dates on each comic so they'd be in order. Is it something to do with how they were uploaded to the library? (In a batch.) But then, the latest comic will ALWAYS be the latest item in the library so I'm not sure why that would change things.

### Current Behavior
Unfortunately, it's not scrolling from beginning to end, but end to beginning, in reverse-chronological order. I've tried changing archive options in the Customize menu, tried flipping the options in both Webcomic Settings on the page and Template Options on the page. Nothing changes the behavior.

It should be noted that the normal comic navigation works fine. 

### Context
This makes the infinite scroll archive effectively useless, as they'd have to, well, infinitely scroll to get to the beginning.

### Example
https://cvilbrandt.naiya.org/new-readers/

- Webcomic Version 5.0.5
- WordPress 4.9.5
- PHP 7.0.30
- Chrome Version 66.0.3359.139

**Comment by mgsisk** [comment]
Hey @pixel-prism! Thank you for reporting this, and apologies for the trouble. The issue is technically with Inkblot… it really needs to be updated for Webcomic 5 (something I'm working on now).

Until I can get my act together with Inkblot, you can force it to respect the order template setting by opening up the `/wp-themes/inkblot/template/webcomic-infinite.php` and replace line 23:

```php
<main role="main" data-webcomic-infinite="<?php the_ID(); ?>" data-webcomic-collection="<?php print get_post_meta(get_the_ID(), 'inkblot_webcomic_collection', true); ?>" data-webcomic-order="<?php print get_post_meta(get_the_ID(), 'inkblot_webcomic_order', true) ?>">
```
with this:
```php
<main role="main" data-webcomic-infinite="order=<?php print get_post_meta(get_the_ID(), 'inkblot_webcomic_order', true) ?>&post_type=<?php print get_post_meta(get_the_ID(), 'webcomic_collection', true); ?>">
```
You may need to specify a collection in the Page's *Webcomic Settings* box

**Comment by pixel-prism** [comment]
That worked great!! Thank you very much!
