### ISSUE TITLE
New Collection makes Old Collection disappear

### ISSUE THREAD

**Issue by pixel-prism** [mgsisk/webcomic#309]
So, I have all my comics in the Tamberlane collection, but I wanted to add a new collection for fanart. When I add a new collection, suddenly the front page no longer loads pages from the Tamberlane collection. I've gone into the Customize / Webcomic & Inkblot / Front Page settings and made sure it was pointing to the correct collection, but nothing shows. 

This has happened with multiple second collections I've tried to create. As soon as I delete the new collection and again direct the homepage to Tamberlane, it works fine again.

### Expected Behavior
I expect that creating a separate collection will allow me to access that collection on another page / another archive / etc without harming the Main Comic collection or making it inaccessible.

### Current Behavior
Any secondary collections will instead cause access to the Main Comic collection to disappear.

### Context
It would be very nice to be able to have, say, a collection of Patreon-locked comics that are separate from the main comic, or a collection of Fanart that can be browsed through. 

### Example
For the record, the site is (as you probably are aware of by now lol): http://cvilbrandt.naiya.org
To reproduce the bug:

- Main collection settings are:
  slug/permalink are both "comic"
  Syndication: include in the main syndication feed is turned on

- Secondary collection settings are:
  slug/permalink are both "patreon"
  Syndication: include in the main syndication feed is turned OFF

- Customize / Webcomic & Inkblot / Front Page is set to:
  Your Latest webcomic, from this collection (Tamberlane)

I'll leave this arrangement for now so you can see it on the live site.

### Environment

- Webcomic 5.0.5
- WordPress 4.9.6
- PHP 7.0.30
- Chrome 66.0.3359.139

**Comment by pixel-prism** [comment]
Interestingly, the Infinite Scroll and Archive pages remain untouched. I assume it's because I've been regularly assigning the collection as I go. I just have no idea why the collection assignation isn't sticking on the front page!

**Comment by mgsisk** [comment]
Thanks for the report @pixel-prism, and apologies for the trouble. It looks like this is an(other) issue with Inkblot, specifically that front page collection customizer setting To force it to use the correct collection, open up `wp-content/themes/inkblot/webcomic/home.php` and change line 21:

```php
'post_type' => get_theme_mod('webcomic_home_collection', '') ? get_theme_mod('webcomic_home_collection', '') : get_webcomic_collections(),
```
to
```php
'post_type' => 'webcomic1', // Or whatever the correct Webcomic collection ID is
```

**Comment by pixel-prism** [comment]
That did the trick!! Thank you so much for taking the time to help with that!

I have one more question about widgets. I'm trying to have a widget on my sidebar that displays the latest comic in another collection. I'm trying to use the Last Webcomic widget but it looks like you have to hard-choose the image it uses. I've also tried Webcomic Media but can't seem to figure out how to get it to dynamically choose the last comic. Any tips here? 

Thank you so much!

**Comment by mgsisk** [comment]
The Last Webcomic Link widget is correct, actually; the trick is to [use a media token](https://github.com/mgsisk/webcomic/wiki/get_webcomic_link_tokens) as the link text. For example, Webcomic will convert `%thumbnail` into the thumbnail-sized comic media for a post.

**Comment by pixel-prism** [comment]
Omg, thank you so much! It's been nearly a decade since I've messed with Wordpress and a lot has changed in that time, haha! Dropped a sub on your paypal; thanks again!
