### ISSUE TITLE
Archive listing pages chronologically but storylines reverse-chronologically

### ISSUE THREAD

**Issue by pixel-prism** [mgsisk/webcomic#310]
For my archive page, I have all the pages listed as thumbnails by storyline, and thankfully all the pages in each storyline are in chronological order!

Unfortunately, the storylines are not in chronological order.

### Expected Behavior
I'm looking to get:
- Chapter 1
- Chapter 2
- Chapter 3

### Current Behavior
It is currently:
- Chapter 3
- Chapter 2
- Chapter 1

### Context
It's not so bad right now with only 3 chapters, but eventually with enough chapters, it's going to be a looooong scroll for new readers to get to Chapter 1.

### Example
https://cvilbrandt.naiya.org/archive/

### Environment

- Webcomic 5.0.5
- WordPress 4.9.6
- PHP 7.0.30
- Chrome 66.0.3359.139

**Comment by mgsisk** [comment]
Hey @pixel-prism, apologies for the trouble. This is another Inkblot issue I need to fix, unfortunately. To force the proper sorting, open up `/wp-content/themes/inkblot/template/webcomic-archive.php` and find this big block of code (lines 26–34):

```php
$webcomic_arguments = array(
	'collection' => get_post_meta(get_the_ID(), 'webcomic_collection', true),
	'webcomics' => get_post_meta(get_the_ID(), 'inkblot_show_webcomics', true),
	'order' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_order', true),
	'target' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_target', true),
	'webcomic_order' => get_post_meta(get_the_ID(), 'inkblot_webcomic_order', true),
	'webcomic_image' => get_post_meta(get_the_ID(), 'inkblot_webcomic_image', true),
	'show_image' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_image', true)
);
```
and add an `orderby` argument, like:

```php
$webcomic_arguments = array(
	'collection' => get_post_meta(get_the_ID(), 'webcomic_collection', true),
	'webcomics' => get_post_meta(get_the_ID(), 'inkblot_show_webcomics', true),
	'order' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_order', true),
	'target' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_target', true),
	'webcomic_order' => get_post_meta(get_the_ID(), 'inkblot_webcomic_order', true),
	'webcomic_image' => get_post_meta(get_the_ID(), 'inkblot_webcomic_image', true),
	'show_image' => get_post_meta(get_the_ID(), 'inkblot_webcomic_term_image', true),
	'orderby' => 'name'
);
```

**Comment by pixel-prism** [comment]
Rad! That worked great! Thanks a million!!
