### ISSUE TITLE
Comic archive thumbnail linked to wrong page

### ISSUE THREAD

**Issue by ykyu** [mgsisk/webcomic#311]
This is likely an Inkblot issue, but in a default collection archive, the webcomic image links to the URL of the most recent page of the collection, rather than the URL of the page it displays. The title of the webcomic page links the correct URL.

### Expected Behavior
All webcomic thumbnails in collection archive link to corresponding page.

### Current Behavior
All webcomic thumbnails in collection archive link to most recent page.

### Example
My website is not currently public, so here is another site using Webcomic + Inkblot with the same issue: https://cvilbrandt.naiya.org/tamberlane/

The page 1 thumbnail erroneously links to page 139, while the page 1 title correctly links to page 1.

### Environment
- Webcomic 5.0.5 
- WordPress 4.9.6

**Comment by mgsisk** [comment]
Thanks for the report @ykyu, and apologies for the trouble. I actually can't seem to duplicate this issue, so I'm not entirely sure what's causing it just yet. As a fix, however, try opening up `/inkblot/webcomic/content.php` and change line 21:

```php
<?php the_webcomic(get_theme_mod('webcomic_archive_size', 'large'), 'self'); ?>
```
to
```php
<?php webcomic_link( '%' . get_theme_mod('webcomic_archive_size', 'large') ); ?>
```

**Comment by ykyu** [comment]
Many thanks! This resolved the issue perfectly.
