### ISSUE TITLE
Quality of Life Suggestion, Webomic Link Shortcode(s)

### ISSUE THREAD

**Issue by Mihari** [mgsisk/webcomic#312]
### Expected Behavior
`[last_webcomic_link]` When used, works as intended.
`[last_webcomic_link collection="webcomicX"]` When used and X being the ID of whatever webcomic is used, does generate that specific link to that and works as intended.

### Current Behavior
`[last_webcomic_link collection="webcomicX"]Link Text Here![/last_webcomic_link]` Now here is where things are different it was expected that shortcode could utilizing a closing portion and process the string between them as the `$link` text as specified in `get_webcomic_link()`. However, the short code will just completely ignore all of that and spit out the same result as if it wasn't there at all.

### Context
For simplicity sake of a general user, it might be nicer if the $link string could be processed as the example above suggests instead of having to link that you have to use link="text" for it to work.

### Example
`[last_webcomic_link collection="webcomicX" link="Link Text"]`This is the correct method of using the shortcode.
`[last_webcomic_link collection="webcomicX"]Link Text[/last_webcomic_link]` This would be nice to have as an option means of specifying the shortcode. That being said I do like the other way as it's nice and clean, but I think for general users the other way would be familar and easy to use, and is also how Webcomic 4.x was.

- Webcomic 5.0.5
- WordPress 4.9.6
- PHP 7.2

**Comment by mgsisk** [comment]
Thanks for the suggestion @Mihari; this appears to be a bug with the `Compat` component, as the shortcode *should* work as you suggest. I'll try to get this fixed for the 5.0.6 release.

**Comment by mgsisk** [comment]
This should be fixed by 5a39344ca4deff0f7e34e929aa8e82cfec9d4d0d
