### ISSUE TITLE
Template Tag to show Storylines and Characters in Comic Page

### ISSUE THREAD

**Issue by TijaArud** [mgsisk/webcomic#318]
Hello there!

I'm in the process of creating a custom theme for Webcomic, but I've run into a mental roadblock.

I'm trying to implement a list of characters featured in a comic page, as well as the featured storyline -- as is found in the Inkblot theme... But try as I might, I can't seem to wrap my head around the template tags to call.

Any help would be greatly appreciated, thanks!

**Comment by mgsisk** [comment]
Hey @TijaArud, apologies for the confusion. The docs are probably a little bit vague, but `webcomic_characters_list()` and `webcomic_storylines_list()` are the tags you want. To display only the characters and storylines associated with the current comic post, you would use them like:

```php
<?php webcomic_characters_list( [ 'object_ids' => get_the_ID() ] ); ?>
```

Most of the arguments those template tags accept are actually documented on the [get_webcomic_terms_list()](https://github.com/mgsisk/webcomic/wiki/get_webcomic_terms_list()) and [get_webcomic_terms()](https://github.com/mgsisk/webcomic/wiki/get_webcomic_terms()) pages.

**Comment by TijaArud** [comment]
Of course -- that makes total sense. I had overlooked the documentation on the get_webcomic_terms_list() and get_webcomic_terms() pages.

Thank you so much -- works like a charm!

**Comment by TijaArud** [comment]
So... I'm back again.

I moved onto creating an archive page like Inkblot's, and am trying to separate it out so that each storyline in a comic has its own section on the archive page. I haven't had time to do much yet, but I assume the method is roughly the same as getting the individual storylines and characters as in my OP?

I'm thinking I'll need to use [webcomic_storylines_list()](https://github.com/mgsisk/webcomic/wiki/webcomic_storylines_list()) and then use [webcomics_list()](https://github.com/mgsisk/webcomic/wiki/webcomics_list()) to pull the correct comic pages... Correct?

**Comment by mgsisk** [comment]
Sort-of. If you look at the arguments for [get_webcomic_terms_list()](https://github.com/mgsisk/webcomic/wiki/get_webcomic_terms_list()), you'll notice it has a `webcomics` argument. So you don't actually have to use both `webcomic_storylines_list()` *and* `webcomics_list()`; you can just use `webcomic_storylines_list()` like:

```php
<?php
webcomic_storylines_list( [
  'format' => '<div class="comic-storylines">{{<hr>}}</div>',
  'link' => '<h2>{{}}</h2>',
  'webcomics' => [
    'link' => '%thumbnail',
  ]
] );
?>
```
Or however you want everything to display out.

**Comment by TijaArud** [comment]
Great -- thanks so much for that!

My only issue now is that I can't pull the associated media for each storyline... I have tried using the following:

`<?php
$webcomic_storyline_media = webcomic_storyline_media();

webcomic_storylines_list( [
    'link' => '<div class="comic-media">{{' . $webcomic_storyline_media . '}}</div>',
] );
?>`

I know I'm missing something obvious, but I can't quite grasp what it is.

**Comment by mgsisk** [comment]
This is another one that might not be so obvious; the `'link` argument on `webcomic_storylines_list` [accepts a number of tokens](https://github.com/mgsisk/webcomic/wiki/get_webcomic_term_link_tokens) that Webcomic will intelligently replace. Try:

```php
<?php
webcomic_storylines_list( [
    'link' => '<div class="comic-media">{{%full}}</div>',
] );
?>
```

**Comment by TijaArud** [comment]
Of course -- now that you've told me, it's so obvious. I don't know why I didn't think of that. I saw the list of accepted tokens, but I didn't think to actually use them.

Thanks again! It's an awesome plugin you've made!

**Comment by TijaArud** [comment]
OK, I know I'm getting a little off-topic now, but I have one last question please...

How can I get the page number for each storyline/chapter? I know there's the token `%count`, but I don't know how to translate that into the array to count up from 1.

What I would like to have is something like this:

Chapter 1
01 ~ 02 ~ 03

Chapter 2
01 ~ 02 ~ 03

**Comment by mgsisk** [comment]
Hey @TijaArud, apologies for the delayed response. There's no easy way to do this at the moment with `webcomic_storylines_list`… but it'd probably make a good feature. Marking this as an enhancement to see if this can be added to a future release.
