### ISSUE TITLE
Navigation buttons are just text

### ISSUE THREAD

**Issue by memoircomics** [mgsisk/webcomic#320]
Hello!

This is the first time I've ever tried to make a website but I think I'm doing pretty okay so far. Everything is working just like I wanted it to--I've made two separate webcomics and a main home page on one domain using the "collections" feature of the plugin.

The only thing that isn't working right now is the navigation buttons. They worked earlier, before I tried separating the webcomics into subdirectories. I've done so much stuff that I don't understand, so I can't figure out for the life of me where I made the mistake! 

The main page is "[memoircomics.com](http://memoircomics.com)", the two webcomics are "[memoircomics.com/thirdkind](http://memoircomics.com/thirdkind)" and "[memoircomics.com/memoircomics](http://memoircomics.com/memoircomics)".

Thank you so much for your help.

**Comment by mgsisk** [comment]
Hey @memoircomics, thanks for using Webcomic! It looks like you have a title on your comic link widgets, but no link text. Adding some link text should get the links working properly.

**Comment by memoircomics** [comment]
@mgsisk, thank you :crying_cat_face: I can't believe it was that simple!

I have one more problem now--at first, each comic showed up three times per post, except for the front page of the site, where it would show up once. 

I figured out just by clicking around that checking the "Place webcomic in the main column" box under the "Webcomic and Inkblot 4 > Layout" tabs made one instance of the comic disappear.

Now the comic repeats twice on each page.

I think  it has something to do with the integration, but I don't know. I'm using "Universal" right now because "Webcomic" makes the comic disappear completely. I switched to a different theme and the comic shows up fine, with only one instance per post.

Can you help me get rid of one of the two? Thank you!

**Comment by mgsisk** [comment]
Webcomic 5's integration options are a bit misleading when it comes to the current version of Inkblot – you actually want to turn off Webcomic 5's integration with Inkblot. That should get rid of the comic duplication.
