### ISSUE TITLE
Conflict with Webcomic after installing WooCommerce

### ISSUE THREAD

**Issue by bluestockinger** [mgsisk/webcomic#323]
Hello

I just thought I would alert you to an issue I discovered today after installing WooCommerce.

After activating the plugin, one is immediately redirected to the setup at: http://localhost/wordpress/wp-admin/admin.php?page=wc-setup

Unfortunately, this throws numerous errors, which I have listed below. These errors occur no matter which theme is activated, as they are linked to the Webcomic plugin.

If I simply deactivate Webcomic, run the WooCommerce setup and then reactivate Webcomic, everything seems to work fine, however, this is not something the average person would necessarily know to do.

The full list of errors are as follows:

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\plugin\settings.php on line 203

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\plugin\settings.php on line 218

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\plugin\settings.php on line 241

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\custom.php on line 37

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\custom.php on line 52

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\generator.php on line 296

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\generator.php on line 311

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\generator.php on line 334

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\matcher.php on line 323

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\matcher.php on line 338

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\matcher.php on line 361

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\settings.php on line 292

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\settings.php on line 307

    ( ! ) Notice: Trying to get property of non-object in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\metabox\media.php on line 35

    ( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to webcomic_collection_exists() must be of the type string, null given, called in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\metabox\media.php on line 35 and defined in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\globals.php on line 1192
    ( ! ) TypeError: Argument 1 passed to webcomic_collection_exists() must be of the type string, null given, called in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\metabox\media.php on line 35 in C:\wamp\www\wordpress\wp-content\plugins\webcomic\lib\collection\globals.php on line 1192

**Comment by mgsisk** [comment]
Thanks for the report, @bluestockinger. I'm not sure how WooCommerce manages to pull up an admin screen with no `WP_Screen` object, but it's an easy fix, at least. 🤷‍♂️

**Comment by bluestockinger** [comment]
No problem, @mgsisk. Who knows how these things get through sometimes, but glad to hear it's an easy fix 😃
