### ISSUE TITLE
Comic collection cannot be deleted, navigation bar won't work for that collection, strange glitched text on "All Comics" page

### ISSUE THREAD

**Issue by bmolulon** [mgsisk/webcomic#324]
So, I'm a complete novice working with WordPress and the Webcomic plugin. I made a practice comic collection just to see how things would work and everything seemed to work fine. I don't know what I did, but somehow, when I went to work on my site the next day, I wasn't able to use the navigation bar underneath my comic. I decided to make a second collection and move everything over to it, and that fixed the navigation problem, but after doing so, I wasn't able to delete the previous comic collection. the actual button in "settings" to delete it was gone. After that, I noticed that the "All Comics" page for the first collection looked corrupted. where you'd usually have the "storylines" and "characters" columns, that specific text (storylinescharacters) was written vertically down the page. I haven't messed with any code, since I have no experience, but I was also testing out the Comic Easel plugin. Perhaps it's not compatible?

Anyway, I'm completely lost. I'd be really grateful for any help you could offer. I just want to make sure this doesn't interfere with my site building or become a major issue for other people.

- Webcomic Version 5.0.6
- WordPress Version 4.9.8
- PHP <unknown. not sure if I'm even using it.>
- Google Chrome

**Comment by mgsisk** [comment]
Hey @bmolulon, apologies for the trouble. I think I can help with some of this:

- For mostly boring technical reasons, you actually *can't* delete the very first collection Webomic creates when it's installed (known as `webcomic1` behind the scenes). It should be safe to leave it there (though, if it really bothers you, I might be able to work up some code to remove it and change your second collection into `webcomic1`).
- The columns on the **All Comics** page might just be too narrow. Try clicking the **Screen Options** tab at the top of the page and unchecking a few columns; the text in the storyline and character columns will probably start looking a little more normal.
- Webcomic and Comic Easel should play relatively well together; I'm not aware of any issues (but let me know if you notice any serious looking errors).
- Just an FYI: WordPress requires PHP, so you're definitely using it (at least veresion 7, as Webcomic requires PHP 7 or greater).

Hope that helps!
