### ISSUE TITLE
Display webcomic thumbnail/first image

### ISSUE THREAD

**Issue by misternek** [mgsisk/webcomic#325]
I'm trying to develop a custom Webcomic theme for my own website, and I'm at the point where I'm creating the archive.php page:

    <div id="gallery">
    <?php if (have_posts()) : ?><?php while (have_posts()) : the_post(); ?>
    
    <a href="<?php the_permalink(); ?>"><?php webcomic_media(); ?></a>
    
    <?php endwhile; ?><?php else : ?>
    <?php endif; ?>
    </div>

It's working fine until I make a webcomic post with more than one piece of media. When I do that it display all of the post's media on the page, when I only want one thumbnail image. I've tried the default Wordpress thumbnail tag and that doesn't return any images. I've also looked at the wiki but it's not entirely clear to me how to configure the tag to just show one image from the post.

Sorry if this sounds like a noob question, I only have the most basic knowledge of PHP.

**Comment by misternek** [comment]
Hi @mgsisk! Unfortunately this code doesn't quite for me. The archive page is still showing all of my gallery post's media:

![galleryissue](https://user-images.githubusercontent.com/42818466/44937308-97bf1b00-ad46-11e8-8591-ce8757e31d28.png)

Here is my entire archive.php file if it helps. I also tried resetting the permalinks and renaming it to archive-webcomic1.php and got the same results.

    <?php get_header(); ?>
    
    <div id="gallery">
    <?php if (have_posts()) : ?><?php while (have_posts()) : the_post(); ?>
    
    <a href="<?php the_permalink(); ?>"><?php webcomic_media( 'full', null, [ 'length' => 1 ] ); ?></a>
    
    <?php endwhile; ?><?php else : ?>
    
    <?php endif; ?>
    </div>
    
    <?php get_footer(); ?>

**Comment by mgsisk** [comment]
Thanks @misternek; totally my fault. The `length` argument requires the `offset` argument, as well, but of course I forgot that. Try this one:

```php
<?php webcomic_media( 'full', null, [ 'offset' => 0, 'length' => 1 ] ); ?>
```
The `offset` and `length` arguments work together; here, they're telling Webcomic "of all the media this post has, start at the first media item (`offset => 0`) and just show one (`length => 1`).

**Comment by misternek** [comment]
This worked perfectly, thank you @mgsisk!
