### ISSUE TITLE
Display Popular Collections?

### ISSUE THREAD

**Issue by tehandeh** [mgsisk/webcomic#328]
I was wondering if theres a way to display a popular collections list? I've been trying to wrap my head around it but tbh I don't even know where to start haha

Thanks in Advance!

**Comment by mgsisk** [comment]
There is not, but that's an interesting idea! It would probably require tracking individual post popularity, and then aggregating that into a "collection" popularity (that could then be queried against for collection lists). Or you could just use post popularity directly, and assume that the collection of the most popular post is the most popular collection, etc.

It might be possible to get this sort of feature without waiting for Webcomic to implement it… combining Webcomic with something like https://wordpress.org/plugins/wordpress-popular-posts/ might do the trick. I'm not familiar with that plugin, however, so I don't know for sure if it would work; the main thing would be having something that both tracks the popularity of posts *and* exposes that information in a way that can be passed to `webcomic_collections_list`…
