### ISSUE TITLE
Fatal Error on webcomic.php

### ISSUE THREAD

**Issue by joeartguy** [mgsisk/webcomic#331]
I updated the Webcomic plugin to 5.0.6, and my site crashed. I was able to restore it but now cannot activate Webcomic, as Wordpress gives me a Fatal Error warning.

I'm using a standard WP install (4.9.8) with the Archimedes theme. No other plugins are running except Askimet Anti-Spam.

The warning WP gives on attempting activation is:

> Parse error: syntax error, unexpected '[', expecting ')' in /hermes/walnaweb10a/b1799/pow.joerosales/htdocs/blogengine/wp-content/plugins/webcomic/webcomic.php on line 22

which just seems to be the PHP version 7 check.

My site's at [joerosales.com](url) and I am welcome to any suggestions.

### Environment

- Webcomic 5.0.6 
- WordPress 4.9.8 
- PHP ?

**Comment by mgsisk** [comment]
Hey @joeartguy, apologies for the trouble. Based on the syntax error, this is almost certainly a PHP version issue; the short array syntax Webcomic uses was introduced in PHP 5.4. If you can, I'd check your hosts control panel and bump PHP up to at least version 7.

**Comment by joeartguy** [comment]
This has solved my problem and I have learned something new. Thank you for your help.
