### ISSUE TITLE
"Random Comic" never shows the thumbnail of the comic it's linking to

### ISSUE THREAD

**Issue by sailorptah** [mgsisk/webcomic#343]
I have the "Random Webcomic Link" widget at the bottom of the sidebar, on comic pages like this one:

https://leifandthorn.com/comic/party-prep-2-22/

The text in "link" is "%medium", and sure enough, it displays a medium thumbnail of a random comic -- but with the URL of an entirely different random comic.

I would like them to be the same! The goal is for the thumbnails to give readers thoughts like "oh yeah, I liked that arc, I want to reread it" or "huh, I don't remember that strip, better go look at it again". If clicking doesn't take them to the strip they're looking at...I'm not sure what purpose it serves, but definitely not this one!

Versions: Wordpress 5.4, Webcomic 5.0.6

**Comment by mgsisk** [comment]
Thanks for the report @sailorptah. I'll have to take a look at how that function works… it definitely shouldn't be using separately-random URL's and images.
