### ISSUE TITLE
No spacing between two media

### ISSUE THREAD

**Issue by SD-Voyez** [mgsisk/webcomic#349]
Hi,

This plugin is really great but i would like that there is no space between two visuals, but I do not see any padding or margin, how can I solve the problem ?

Exemple here : https://www.dede-tattoo.com/gags/rencontre-du-3eme-type/

![image](https://user-images.githubusercontent.com/67580878/88932782-d20cfc00-d27e-11ea-8ebc-33e0cbae8e7d.png)

Thank you !

**Comment by sailorptah** [comment]
Answered this on Discord, but I figured I'd copy it here for anybody who finds this thread on google...

It's the kind of edit you make with a child theme:
https://www.hostinger.com/tutorials/how-to-create-wordpress-child-theme

And here's the CSS to add (make the number bigger or smaller to get the amount of spacing you want, decimals are fine):

```
.webcomic-image img {
    padding-bottom: 1em;
}
```
