### ISSUE TITLE
Shortcode to include a specific character description?

### ISSUE THREAD

**Issue by sailorptah** [mgsisk/webcomic#365]
Can I modify [webcomic_character_description] (or anything else) to call the description of a specific character, no matter what page I'm using it on?

For example, the description of this character (tag ID "13"), a 3-sentence line of text that appears at the top of their tagged appearances:

https://leifandthorn.com/character/tiernan/

If I'm making an entry for that character on the generic Cast Page, is there a shortcode I can use to just automatically insert their pre-existing description?

**Comment by mgsisk** [comment]
`[webcomic_character_description]` can take a term ID and a collection, like:

```
[webcomic_character_description term="13" collection="1"]
```

You may need to specify both for it to work, depending on the page.
