### ISSUE TITLE
Main link to webcomic suddenly stopped working

### ISSUE THREAD

**Issue by mynfel** [mgsisk/webcomic#371]
Hi there - I am running an older version of Webcomic (4) and I should probably look at upgrading, but in the meantime I did notice that the link that's supposed to take you to the latest page of the webcomic no longer works and takes you to some random placeholder page I probably set up back in 2012. 

https://sadsausagedogs.com/?page_id=32
 
Also it looks like my Archives are suddenly all blank now as well, and I haven't touched them, so I don't know what happened. 

(https://sadsausagedogs.com/?page_id=508)

I don't mind trying to upgrade to Webcomic 5 but I'm rather afraid of what else it might break, but in the meantime, is there a setting that would at least get the main link back up and running? (Sorry if this is something I should already know.) :(

Thanks

### Environment

- Webcomic 4.4.1
- WordPress 5.8
- PHP 7.2
-

**Comment by mgsisk** [comment]
Apologies for the trouble, @mynfel. I'm not entirely sure what's going on with the archive… can you share how that page is setup / the settings for that page?

For the latest comic link, I'm guessing you're referring to the Fox & Willow link in the menu. It looks like it's hard coded to that specific page, for some reason. If you can edit that menu item, try changing the link to `https://sadsausagedogs.com/?last_webcomic=webcomic2`, which does appear to work.

**Comment by mynfel** [comment]
Okay - so that link does work. In poking around - that other page was listed as the Webcomic Homepage under the template so I think in the version I have that has always just listed itself as the starting point of the entire comic? It's worked that way for years so I'm not sure what broke - though when I take a closer look at the page it actually says : It looks like [Webcomic](http://wordpress.org/plugins/webcomic) is not installed or activated. This template will not affect the appearance of this page.

I have NO idea why it thinks that - I can still add comic pages and whatnot and that seems to work. If I look in plugins, Webcomic is listed as active.

As far as the archive goes - it's got the same issue as above where it thinks it doesn't have the Webcomic plug in installed. (If I recall a few years ago, you helped me out and did throw some custom code into the archive page at one point but I don't think that's relevant.)

Thank you for all your help!

**Comment by mgsisk** [comment]
Ah, ok; I think I've seen this before. The issue is probably that Inkblot has it's own set of functions that kick in if Webcomic isn't available… and for some reason (maybe changes in recent versions of WordPress?) these functions get loaded *before* Webcomic itself is loaded. Only one set of the functions can exist at a time, so if the Inkblot set gets loaded before the Webcomic set, Inkblot will assume Webcomic *isn't* installed and behave accordingly.

As a workaround, open up Inkblot's `/-/php/tags.php` file and find the `webcomic()` function (it starts on line 17 in the Theme Directory release you can download from wordpress.org). Line 18 should be:

`return false;`

Change it to:

`return true;`

This will force Inkblot to behave like Webcomic is installed (which it is in this case) and get the Webcomic-specific template files working again.

**Comment by mynfel** [comment]
No dice. I changed it in both inkblot and the inkblot master just in case, but it doesn't seem to work. :(

**Comment by mynfel** [comment]
Would it be worth just trying to upgrade at this point?

**Comment by mgsisk** [comment]
Honestly, upgrading might cause more headaches. Do you mind sending me an email on this? I'm thinking if I can look at your site directly maybe I can diagnose the issue.

**Comment by mynfel** [comment]
Yup - I actually sent you an email a week or two ago before I posted here to ask - let me know if you didn't get it. (might be in your spam?)

**Comment by mgsisk** [comment]
Ah, apologies; could you [email me](mailto:me@mgsisk.com) again? My email must've ate it as I'm not finding anything in my junk folder, either.

**Comment by mynfel** [comment]
Done! :D  Thanks!

**Comment by mynfel** [comment]
Thank you so much for fixing the issue! :D

**Comment by mgsisk** [comment]
No problem! For others looking at this issue: the fix in this case was to remove the `webcomic()` checks from Inkblot's Webcomic-specific template files.
