### ISSUE TITLE
Support option text and checkboxes overlap and are unusable

### ISSUE THREAD

**Issue by thesamuraiwho** [mgsisk/webcomic#385]
**Expected Behavior**\
Support options checkboxes and text appear legible and not overlapping.

**Current Behavior**\
Text and checkboxes for the Support setting overlap and clicking on checkboxes does not reliably set settings correctly.

**Reproduction Steps**\
Running on Wordpress 6.5.2 with the following plugins activated with the Astra 4.6.12 theme:

- Webcomic 5.0.8

**Suggested Fix**\
Text and checkboxes for the Support section should not overlap.

**Context**\

![image](https://github.com/mgsisk/webcomic/assets/60624566/7da315ed-a165-4aaf-9a11-354164b6438f)

Thanks for the help! I love using Webcomic and only after a few wordpress upgrades did I notice the support section overlapping like this. I appreciate your help. Please let me know if you have any further questions. 😁

**Comment by ykyu** [comment]
This should fix it.

In: `/src/lib/collection/settings/general-inc-field-supports.php`

Find: ` class="check-column"`
Replace All: 

^ that is, replace it with nothing. Just delete that class.

**Comment by thesamuraiwho** [comment]
Thank you so much for the help @ykyu! You're a life saver. Those changes worked perfectly.
