### ISSUE TITLE
Limit Archive to current Collection or StoryLine

### ISSUE THREAD

**Issue by foxglove1028** [mgsisk/webcomic#46]
I have looked through all the documentation but cannot find out how to limit the dropdown collection to only the current collection and not to include the other other collections. Any insight or suggestions would be greatly appreciated. Thank you.

Link to the test comic : http://www.dragonrageseishi.com/archive/weeee/

I'm still working on the collections page  but the comic page should be fine.

**Comment by ashikai** [comment]
If I might hijack this for a related question...

Is there a way to auto-detect the current storyline and then list all the pages in that storyline? I dug through the wiki and couldn't find any pre-defined parameter I could use to do this. It seemed like it was all storylines + pages or nothin'. 

Thank you! >w<
